import { Box } from '@mui/material';
import { getServerSession } from 'next-auth';

import AuthProvider from '../../contexts/AuthContext';
import Footer from '../../features/footer/Footer';
import Navbar from '../../features/navbar/Navbar';

export const metadata = {
  title: 'Ace My Exams',
  description: 'Generated by create next app',
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <>
      <AuthProvider session={session} >
        <Box sx={{display: 'flex', minHeight: '100vh', flexDirection: 'column'}}>
          <Navbar />
          <main style={{flex: 1}}>{children}</main>
          <Footer />
        </Box>
      </AuthProvider>
    </>
  );
}