import Navbar from "@/components/common/Navbar/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ace My Exams",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
