import Navbar from '@/features/navbar/Navbar';

export const metadata = {
  title: 'Ace My Exams',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
